import { useState } from "react";
import { useTranslation } from "react-i18next";
import { useAppStore } from "../store";
import { request } from "../backend";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Check, Copy } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";

export function SettingsWebUIDialog({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const { t } = useTranslation();
  const { webUIStatus, pushGlobalErrorMessage } = useAppStore();
  const [copied, setCopied] = useState(false);
  const [customPort, setCustomPort] = useState<string>("");
  const [customToken, setCustomToken] = useState<string>("");

  const handleToggle = async (checked: boolean) => {
    try {
      if (checked) {
        const portNum = customPort.trim() ? parseInt(customPort, 10) : undefined;
        const status = await request.startWebUIServer({
          port: portNum && !isNaN(portNum) ? portNum : undefined,
          token: customToken.trim() || undefined,
        });
        useAppStore.getState().setWebUIStatus(status);
      } else {
        const status = await request.stopWebUIServer();
        useAppStore.getState().setWebUIStatus(status);
      }
    } catch (err) {
      pushGlobalErrorMessage(err instanceof Error ? err.message : String(err));
    }
  };

  const handleCopy = () => {
    if (webUIStatus.url) {
      navigator.clipboard.writeText(webUIStatus.url);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent showCloseButton={true} className="sm:max-w-md">
        <DialogHeader className="mb-2 gap-1">
          <DialogTitle className="flex items-center gap-1 text-md">
            {t("settings.webui.title", "WebUI")}
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-4 mb-2 pt-2 p-1">
          <div className="flex items-center justify-between">
            <h3 className="text-sm text-foreground/80">
              {t("settings.webui.enableAccess", "Enable WebUI Access")}
            </h3>
            <Switch checked={webUIStatus.enabled} onCheckedChange={handleToggle} />
          </div>

          {!webUIStatus.enabled && (
            <div className="flex gap-2 mt-2">
              <div className="flex flex-col gap-2 flex-1">
                <span className="text-xs text-muted-foreground">
                  {t("settings.webui.port", "Port:")}
                </span>
                <Input
                  type="text"
                  placeholder="8080"
                  value={customPort}
                  onChange={(e) => setCustomPort(e.target.value)}
                  disabled={webUIStatus.enabled}
                  className="h-8 text-xs! font-mono"
                />
              </div>
              <div className="flex flex-col gap-2 flex-2">
                <span className="text-xs text-muted-foreground">
                  {t("settings.webui.token", "Token:")}
                </span>
                <Input
                  type="text"
                  placeholder={t("settings.webui.autoGenerated", "Auto-generated")}
                  value={customToken}
                  onChange={(e) => setCustomToken(e.target.value)}
                  disabled={webUIStatus.enabled}
                  className="h-8 text-xs! font-mono"
                />
              </div>
            </div>
          )}

          {webUIStatus.enabled && webUIStatus.url && (
            <div className="flex flex-col gap-2 mt-4">
              <span className="text-xs text-muted-foreground">
                {t("settings.webui.accessUrl", "Access URL:")}
              </span>
              <div className="flex items-center gap-2">
                <Input
                  type="text"
                  readOnly
                  value={webUIStatus.url}
                  className="h-8 text-xs! font-mono text-foreground/80 focus-visible:ring-0.5 bg-background"
                />
                <Button
                  variant="outline"
                  size="icon"
                  className="size-8 shrink-0"
                  onClick={handleCopy}
                  title={t("settings.webui.copy", "Copy")}
                >
                  {copied ? (
                    <Check className="size-4 text-green-500" />
                  ) : (
                    <Copy className="size-4" />
                  )}
                </Button>
              </div>
            </div>
          )}
          <p className="text-xs text-muted-foreground mt-1">
            {t(
              "settings.webui.note",
              "Note: This URL contains a temporary token. The WebUI will be disabled when you restart the application.",
            )}
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
}
