import { useState } from "react";
import { useTranslation } from "react-i18next";
import { useAppStore } from "../../store";
import { request, isWebUI } from "../../backend";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Check, Copy } from "lucide-react";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { extractErrorMessage } from "@/lib/utils";
import { useMessage } from "../providers/message";

export function SettingsWebUI() {
  const { t } = useTranslation();
  const { webUIStatus } = useAppStore();
  const { toast } = useMessage();
  const [copied, setCopied] = useState(false);
  const [customPort, setCustomPort] = useState<string>("");
  const [customToken, setCustomToken] = useState<string>("");

  const handleToggle = async (checked: boolean) => {
    try {
      if (checked) {
        const portNum = customPort.trim() ? parseInt(customPort, 10) : undefined;
        const status = await request.startWebUIServer({
          port: portNum && !isNaN(portNum) ? portNum : undefined,
          token: customToken.trim() || undefined,
        });
        useAppStore.getState().setWebUIStatus(status);
      } else {
        const status = await request.stopWebUIServer();
        useAppStore.getState().setWebUIStatus(status);
      }
    } catch (err) {
      toast.error(
        extractErrorMessage(err) ||
          t("settings.webui.updateFailed", "Failed to update configuration."),
      );
    }
  };

  const handleCopy = () => {
    if (webUIStatus.url) {
      navigator.clipboard.writeText(webUIStatus.url);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    }
  };

  if (isWebUI) {
    return (
      <div className="flex-1 flex flex-col h-full">
        <div className="space-y-6 px-5 py-4 w-full max-w-4xl mx-auto">
          <div>
            <h3 className="text-lg font-medium">{t("settings.webui.title", "WebUI Settings")}</h3>
            <p className="text-sm text-muted-foreground">
              {t(
                "settings.webui.disabledInWebUI",
                "WebUI configuration is disabled when running inside the browser.",
              )}
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex-1 flex flex-col h-full">
      <ScrollArea className="flex-1 overflow-hidden">
        <div className="space-y-6 px-5 py-4 w-full max-w-4xl mx-auto">
          <div>
            <h3 className="text-lg font-medium">{t("settings.webui.title", "WebUI Settings")}</h3>
            <p className="text-sm text-muted-foreground">
              {t("settings.webui.desc", "Configure remote access to the Fello interface.")}
            </p>
          </div>
          <div className="space-y-4 mb-2 pt-2 p-1">
            <div className="flex items-center justify-between">
              <h3 className="text-sm text-foreground/70">
                {t("settings.webui.enable", "Enable WebUI")}
              </h3>
              <Switch checked={webUIStatus.enabled} onCheckedChange={handleToggle} />
            </div>

            {!webUIStatus.enabled && (
              <div className="flex gap-2 mt-2">
                <div className="flex flex-col gap-2 flex-1">
                  <span className="text-xs text-muted-foreground">
                    {t("settings.webui.port", "Port:")}
                  </span>
                  <Input
                    type="text"
                    placeholder="8080"
                    value={customPort}
                    onChange={(e) => setCustomPort(e.target.value)}
                    disabled={webUIStatus.enabled}
                    className="h-8 text-xs! font-mono"
                  />
                </div>
                <div className="flex flex-col gap-2 flex-2">
                  <span className="text-xs text-muted-foreground">
                    {t("settings.webui.token", "Token:")}
                  </span>
                  <Input
                    type="text"
                    placeholder={t("settings.webui.autoGenerated", "Auto-generated")}
                    value={customToken}
                    onChange={(e) => setCustomToken(e.target.value)}
                    disabled={webUIStatus.enabled}
                    className="h-8 text-xs! font-mono"
                  />
                </div>
              </div>
            )}

            {webUIStatus.enabled && webUIStatus.url && (
              <div className="flex flex-col gap-2 mt-4">
                <span className="text-xs text-muted-foreground">
                  {t("settings.webui.accessUrl", "Access URL:")}
                </span>
                <div className="flex items-center gap-2">
                  <Input
                    type="text"
                    readOnly
                    value={webUIStatus.url}
                    className="h-8 text-xs! font-mono text-foreground/70 focus-visible:ring-0.5 bg-background"
                  />
                  <Button
                    variant="outline"
                    size="icon"
                    className="size-8 shrink-0"
                    onClick={handleCopy}
                    title={t("settings.webui.copy", "Copy")}
                  >
                    {copied ? (
                      <Check className="size-4 text-green-500" />
                    ) : (
                      <Copy className="size-4" />
                    )}
                  </Button>
                </div>
              </div>
            )}
            <p className="text-xs text-muted-foreground mt-1">
              {t(
                "settings.webui.note",
                "Note: This URL contains a temporary token. The WebUI will be disabled when you restart the application.",
              )}
            </p>
          </div>
        </div>
      </ScrollArea>
    </div>
  );
}
